const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS"
const GET_CONSTRUCT_SUCCESS = "GET_CONSTRUCT_SUCCESS"
const REMOVE_CONSTRUCT_ELEMENT = "REMOVE_CONSTRUCT_ELEMENT"
const GET_INGREDIENT_DETAILS = "GET_INGREDIENT_DETAILS"
const GET_ID_INGREDIENT = "GET_ID_INGREDIENT"
const GET_ORDER_NUMBER = "GET_ORDER_NUMBER"
const GET_TOTAL_PRICE = "GET_TOTAL_PRICE"

export { 
  GET_INGREDIENTS_SUCCESS, 
  GET_CONSTRUCT_SUCCESS, 
  REMOVE_CONSTRUCT_ELEMENT,
  GET_INGREDIENT_DETAILS,
  GET_ID_INGREDIENT,
  GET_ORDER_NUMBER,
  GET_TOTAL_PRICE
}